apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: flask-app-cluster
  region: us-east-1
  version: "1.27"  # ✅ Use a currently supported version

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
